In [1]:
#---------------------- 讀 Query的 List ------------------------------------

#querylist = open('C:/Users/Ray/Desktop/資訊檢索/Homework1/query_list.txt','r')
#print(querylist.read())

## Open file
fp = open('C:/Users/Ray/Desktop/資訊檢索/Homework1/query_list.txt','r')
ql = [ ]
line = fp.readline()
#querylist.append(line)

## 用 while 逐行讀取檔案內容，直至檔案結尾
while line:
 #   print (line)
    line = line.replace('\n','')
    ql.append(line)
    line = fp.readline()
 
fp.close()
#print (ql)


#---------------------- 讀 DOC 的 List ----------------------------------------

#doclist = open('C:/Users/Ray/Desktop/資訊檢索/Homework1/doc_list.txt','r')
#print(doclist.read())

## Open file
fp = open('C:/Users/Ray/Desktop/資訊檢索/Homework1/doc_list.txt','r')
docl = [ ]
line = fp.readline()
#querylist.append(line)

## 用 while 逐行讀取檔案內容，直至檔案結尾
while line:
 #   print (line)
    line = line.replace('\n','')
    docl.append(line)
    line = fp.readline()
 
fp.close()
#print (docl)


In [2]:
#------------------------- 讀且取每個 Query 內的字 ----------------------------

# Open file
qryl = 0
querylist = [ ]

while qryl < len(ql) :
    fp = open('C:/Users/Ray/Desktop/資訊檢索/Homework1/Query/'+ql[qryl],'r')
    qlt = fp.read()
    qlt = qlt.replace('-1','')
    qlt = qlt.split()
    querylist = querylist + qlt
    fp.close()
    qryl += 1

    
#print(total)
querylist = list(set(querylist))

voc = querylist

print(voc)
print(len(voc))


['1877', '37225', '32022', '23840', '34206', '1542', '8889', '7517', '33261', '29686', '42785', '36249', '22356', '26429', '3388', '14115', '14687', '2231', '978', '5491', '24311', '32580', '25590', '43120', '38988', '11486', '24881', '2715', '41613', '14628', '10705', '19448', '48728', '10817', '18724', '27631', '3428', '3103', '14468', '28534', '2113', '1141', '34975', '1774', '40635', '8115', '20632', '870', '2257', '11054', '7466', '25494', '2938', '16743', '8675', '11714', '27571', '5624', '46263', '1521', '30133', '10369', '2847', '12030', '15564', '13925', '13910', '16974', '18828', '15729', '9242', '653', '21072', '1330', '347', '36961', '3439', '19217', '10968', '25467', '12592', '19671', '13482', '1190', '1145', '39227', '26828', '38383', '17262', '484', '16234', '29890', '24546', '24488', '27646', '44394', '21245', '33886', '30149', '8895', '10907', '13149', '29053', '18528', '596', '2710', '33878', '49949', '30550', '47613', '379', '32554', '10654', '7935', '954', '25150', 

In [3]:
#------------------------ 讀且取每個 Doc 內的字 --------------------------------

# Open file
dcl = 0
doc = [ ]

#total = querylist


while dcl < len(docl) :
    fp = open('C:/Users/Ray/Desktop/資訊檢索/Homework1/Document/'+docl[dcl],'r')
    i = 0
    while i < 3:
        buffer = fp.readline()
        i += 1
    
    doc = fp.read()
    doc = doc.replace('-1','')
    doc = doc.split()
    voc = voc + doc
    voc = list(set(voc))
    
    fp.close()
    dcl += 1
    
print(voc)
print(len(voc))


['26298', '42618', '36751', '1597', '23528', '36742', '37225', '19305', '24876', '22389', '30119', '34206', '26797', '34768', '30580', '26000', '11989', '17104', '27297', '47661', '19440', '18563', '20637', '9286', '28344', '12179', '28793', '36249', '10018', '4008', '33632', '7864', '29008', '26429', '37210', '17285', '7776', '49735', '36332', '33885', '8636', '44549', '978', '39971', '3155', '47264', '16090', '32678', '8446', '11945', '33466', '43659', '37594', '587', '25590', '35849', '12783', '26435', '16887', '24458', '1576', '4554', '884', '44207', '7879', '21619', '40068', '3292', '2147', '41613', '26006', '14628', '25698', '16781', '15823', '10705', '43988', '35278', '9444', '20259', '40745', '30075', '20826', '7429', '25794', '10760', '3428', '34495', '43835', '16789', '1915', '1591', '27969', '30807', '31265', '18935', '33889', '24312', '40148', '32903', '34922', '8115', '45535', '8103', '4124', '2905', '5878', '2915', '38483', '41436', '44715', '870', '47840', '39719', '2558

In [4]:
import numpy as np
import pandas as pd

tfd = np.zeros( (len(voc), len(docl)), dtype=np.int )
print(tfd)



[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [5]:
idf = [ ]
idf = np.zeros( (len(voc), 1), dtype=np.float )
print(idf)

[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


In [6]:
dcl = 0
x = 0
while dcl < len(docl) :
    fp = open('C:/Users/Ray/Desktop/資訊檢索/Homework1/Document/'+docl[dcl],'r')
    
    i = 0
    while i < 3:
        buffer = fp.readline()
        i += 1
    
    doc = fp.read()
    doc = doc.replace('-1','')
    doc = doc.split()
    
    #print(doc)

    x = 0
    for w in voc :
        #print(w)
        for dc in doc :
            #print(dc)
            if w == dc :
                tfd[x][dcl] += 1
        x += 1
        #if(x == 100) : break
        
    #print(np.unique(tfd, axis=0))
        
    fp.close()
    dcl += 1
    
print(tfd)
print(idf)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [2 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


In [7]:

tfq = np.zeros( (len(voc), len(ql)), dtype=np.int )
print(tfq)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [8]:
qryl = 0
while qryl < len(ql) :
    fp = open('C:/Users/Ray/Desktop/資訊檢索/Homework1/Query/'+ql[qryl],'r')
    qlt = fp.read()
    qlt = qlt.replace('-1','')
    qlt = qlt.split()

    
    x = 0
    for w in voc :
        for q in qlt :
            if w == q :
                tfq[x][qryl] += 1
        #print("-------------------------------------------")
        x += 1
        #if(x == 100) : break
            
    fp.close()
    qryl += 1
    
    
print(np.unique(tfq, axis=0))
print(tfq)

[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  1]
 [ 0  0  0 ...  0  0  2]
 ...
 [ 4  4  1 ...  1  8 25]
 [ 6  0  1 ...  0  0  5]
 [12 12  7 ...  4 13 89]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [9]:
for i in range(len(voc)) :
    for j in range(len(docl)) :
        if tfd[i][j] > 0 :
            idf[i][0] += 1

print(idf.shape)
#print(tfd[0], np.unique(tfd[0]))
#print(np.sum(tfd[0]))

(13353, 1)


In [10]:
import math 

for i in range(len(voc)) :
    if idf[i][0] != 0 :
        idf[i][0] = len(docl) / idf[i][0]
        idf[i][0] = math.log(idf[i][0],10) 
        
print(idf)


[[2.75300822]
 [2.87794695]
 [2.87794695]
 ...
 [2.87794695]
 [1.43599011]
 [3.35506821]]


In [11]:
tfidfd = [ ]

#tfdidf = np.matmul()

tfidfd = np.zeros( (len(voc), len(docl)), dtype=np.float )
print(tfidfd)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [12]:

for i in range(len(voc)) :
    for j in range(len(docl)) :
        tfidfd[i][j] = tfd[i][j] * idf[i][0]

'''
for i in range(len(docl)) :
    tfdidf.append(np.multiply(tfd[:,i], idf))

tfdidf = np.asarray(tfdidf)    
''' 
#idf = idf.reshape(1,-1)
#print(tfd[:,0])
#print(np.multiply(tfd[:,0], idf))
#print(np.unique(tfidfd))

print(tfidfd)

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [2.87198023 0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [13]:
tfidfq = [ ]

tfidfq = np.zeros( (len(voc), len(ql)), dtype=np.float )
print(tfidfq)


for i in range(len(voc)) :
    for j in range(len(ql)) :
        tfidfq[i][j] = tfq[i][j] * idf[i][0]
'''
for i in range(len(ql)) :
    tfqidf.append(np.multiply(tfq[:,i], idf))

tfqidf = np.asarray(tfqidf)    
''' 
#idf = idf.reshape(1,-1)
#print(tfd[:,0])
#print(np.multiply(tfd[:,0], idf))
print(np.unique(tfidfq))

print(tfidfq)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[0.00000000e+00 3.83906881e-03 4.79883601e-03 5.75860321e-03
 6.71837041e-03 7.67813761e-03 8.63790481e-03 1.15172064e-02
 1.24769736e-02 1.43965080e-02 1.82355768e-02 2.59137144e-02
 4.39503637e-02 8.32265998e-02 8.54192809e-02 8.79007274e-02
 1.31851091e-01 1.47433839e-01 1.56136336e-01 1.66453200e-01
 1.75801455e-01 1.87455534e-01 2.05541193e-01 2.06157213e-01
 2.28936799e-01 2.49679799e-01 2.63702182e-01 2.94867678e-01
 3.07652546e-01 3.12272673e-01 3.13675521e-01 3.15257652e-01
 3.28943690e-01 3.32906399e-01 3.74911067e-01 4.03245171e-01
 4.11082385e-01 4.12314426e-01 4.23102092e-01 4.38088159e-01
 4.39503637e-01 4.57873598e-01 4.65766504e-01 4.68409009e-01
 4.82329379e-01 4.87011845e-01 4.88780867e-01 4.90557125e-01
 5.03198606e-01 5.09970166e-01 5.11212784e-01 5.23838512e-01
 5.38164367e-01 5.40820611e-01 5.46857233e-01 5.654

In [14]:
from sklearn.metrics.pairwise import cosine_similarity
'''
tfdidf = tfdidf.reshape(13353,-1)
tfqidf = tfqidf.reshape(13353,-1)
print(tfdidf.shape, tfqidf.shape)
'''
#sim = tfdidf[:,0:2].dot(tfqidf[:,0:2].T)
#norms = np.array([np.sqrt(np.diagonal(sim))])
#user_similarity=(sim / norms / norms.T)

#print(user_similarity)

result = [ ]

result = np.zeros( (len(ql), len(docl)), dtype=np.float )
print(result)


for i in range(len(ql)) :
    for j in range(len(docl)) :
        result[i][j] = cosine_similarity([tfidfd[:,j]], [tfidfq[:,i]])

print(result)
#print(cosine_similarity([tfidfd[:,0]], [tfidfq[:,0]]))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0.01813137 0.01159905 0.01026837 ... 0.00354355 0.01594927 0.0097639 ]
 [0.00922151 0.0331791  0.0191479  ... 0.00858656 0.01064115 0.48291561]
 [0.00626615 0.01769752 0.02264975 ... 0.01590043 0.00727876 0.00812547]
 ...
 [0.00602921 0.05517025 0.02292006 ... 0.01314706 0.01198727 0.00787028]
 [0.00447445 0.04199106 0.01683888 ... 0.00861413 0.00276179 0.005237  ]
 [0.02994705 0.02667797 0.03625989 ... 0.03083624 0.01581852 0.05349807]]


In [15]:
ranking = pd.DataFrame(result, index = ql, columns=docl)
print(ranking)


             VOM19980220.0700.0166  VOM19980220.0700.0221  \
20001.query               0.018131               0.011599   
20002.query               0.009222               0.033179   
20005.query               0.006266               0.017698   
20013.query               0.006336               0.003763   
20015.query               0.085146               0.089560   
20020.query               0.009496               0.029844   
20023.query               0.029454               0.041992   
20039.query               0.020120               0.013934   
20048.query               0.019836               0.027449   
20070.query               0.000569               0.011905   
20071.query               0.015151               0.018798   
20076.query               0.028090               0.082182   
20088.query               0.002459               0.012318   
20089.query               0.006029               0.055170   
20091.query               0.004474               0.041991   
20096.query             

In [16]:
ranking = ranking.sort_values(by = ql[0],ascending= False, axis=1)
ranking

VOM19980225.0900.0714  VOM19980226.0900.2338  \
20001.query               0.250473               0.243113   
20002.query               0.032928               0.035189   
20005.query               0.035825               0.031549   
20013.query               0.013677               0.018472   
20015.query               0.093787               0.043487   
20020.query               0.033870               0.042604   
20023.query               0.017339               0.031370   
20039.query               0.061727               0.048649   
20048.query               0.046330               0.046116   
20070.query               0.031663               0.018559   
20071.query               0.041651               0.033569   
20076.query               0.043531               0.024690   
20088.query               0.017381               0.018563   
20089.query               0.015910               0.013785   
20091.query               0.011322               0.021506   
20096.query               0.135747               0.075057   

             VOM19980227.0900.2564  VOM19980221.0700.2087  \
20001.query               0.237228               0.232536   
20002.query               0.029072               0.022090   
20005.query               0.056409               0.043677   
20013.query               0.012069               0.007114   
20015.query               0.042703               0.051624   
20020.query               0.016977               0.014293   
20023.query               0.009093               0.011914   
20039.query               0.076538               0.036571   
20048.query               0.028893               0.052215   
20070.query               0.017121               0.012857   
20071.query               0.059213               0.029123   
20076.query               0.022441               0.029949   
20088.query               0.010994               0.019387   
20089.query               0.008817               0.009849   
20091.query               0.010172               0.007417   
20096.query               0.071308               0.061559   

             VOM19980303.0900.3083  VOM19980605.0730.0189  \
20001.query               0.232471               0.231231   
20002.query               0.016147               0.032884   
20005.query               0.014201               0.034129   
20013.query               0.014062               0.014746   
20015.query               0.020815               0.045850   
20020.query               0.014524               0.007775   
20023.query               0.013048               0.010748   
20039.query               0.061630               0.023749   
20048.query               0.026200               0.051967   
20070.query               0.011291               0.018792   
20071.query               0.046368               0.032554   
20076.query               0.011515               0.022879   
20088.query               0.009866               0.011495   
20089.query               0.009246               0.001794   
20091.query               0.011084               0.010564   
20096.query               0.053514               0.065539   

             VOM19980317.0900.2174  VOM19980605.0900.0196  \
20001.query               0.227445               0.227127   
20002.query               0.025383               0.032300   
20005.query               0.068908               0.033523   
20013.query               0.006526               0.014485   
20015.query               0.013042               0.045313   
20020.query               0.007873               0.009171   
20023.query               0.000461               0.010557   
20039.query               0.061600               0.023327   
20048.query               0.014234               0.051044   
20070.query               0.006839               0.018458   
20071.query               0.029870               0.031976   
20076.query               0.005966               0.025307   
20088.query               0.001853               0.011291   
20089.query               0.006312           

In [17]:
name = [ ]

f = open('M10715086.txt','w') 
f.write("Query,RetrievedDocuments\n")
f.close()

f = open('M10715086.txt','a') 

for i in range(len(ql)) :
    f.write(ql[i] + ',')
    ranking = ranking.sort_values(by = ql[i],ascending= False, axis=1)
    name = ranking.columns
    name = np.asarray(name)
    for j in range(len(docl)):
        f.write(name[j] + ' ')
    f.write('\n')

f.close()